# Generated by Django 2.1.5 on 2020-04-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
