# Generated by Django 2.1.5 on 2020-04-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_comment_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
